import { CarData, Mission, PlayerProfile, GameSettings } from '../types';

export const CARS_CATALOG: CarData[] = [
  {
    id: 'apex-gtr',
    name: 'Apex GT-R',
    tier: 'STREET',
    description: 'A finely tuned street warrior with rapid cornering response and balanced top speed.',
    price: 0,
    unlocked: true,
    stats: {
      topSpeed: 210,
      acceleration: 6.5,
      handling: 7.5,
      nitroCapacity: 6.0,
    },
    primaryColor: '#00e5ff', // Cyan
    availableColors: ['#00e5ff', '#ff0055', '#ffaa00', '#ffffff', '#111111', '#00ff66'],
    underglowColor: '#00e5ff',
    modelType: 'gt',
  },
  {
    id: 'cyber-phantom',
    name: 'Cyber Phantom',
    tier: 'SPORT',
    description: 'Angular aerodynamics paired with high-torque twin electric motors for instant acceleration.',
    price: 750,
    unlocked: false,
    stats: {
      topSpeed: 240,
      acceleration: 8.0,
      handling: 7.8,
      nitroCapacity: 7.2,
    },
    primaryColor: '#9d00ff', // Electric Purple
    availableColors: ['#9d00ff', '#ff0077', '#00e5ff', '#222222', '#e6fb04'],
    underglowColor: '#bf00ff',
    modelType: 'coupe',
  },
  {
    id: 'vortex-hypersport',
    name: 'Vortex Hypersport',
    tier: 'HYPER',
    description: 'Aerospace-grade composite monocoque chassis engineered for extreme highway speeds.',
    price: 1800,
    unlocked: false,
    stats: {
      topSpeed: 275,
      acceleration: 8.8,
      handling: 8.4,
      nitroCapacity: 8.5,
    },
    primaryColor: '#ff2a00', // Fiery Crimson
    availableColors: ['#ff2a00', '#ffaa00', '#0066ff', '#1a1a1a', '#e0e0e0'],
    underglowColor: '#ff3b00',
    modelType: 'hypercar',
  },
  {
    id: 'nebula-roadster',
    name: 'Nebula Roadster',
    tier: 'SPORT',
    description: 'Open-cockpit speedster with magnetic suspension allowing razor-sharp lane switches.',
    price: 3200,
    unlocked: false,
    stats: {
      topSpeed: 260,
      acceleration: 8.2,
      handling: 9.6,
      nitroCapacity: 8.0,
    },
    primaryColor: '#00ffaa', // Mint Neon
    availableColors: ['#00ffaa', '#ff00aa', '#3300ff', '#ffffff', '#222222'],
    underglowColor: '#00ffaa',
    modelType: 'roadster',
  },
  {
    id: 'quantum-venom',
    name: 'Quantum Venom',
    tier: 'HYPER',
    description: 'Aggressive track monster boasting active aero flaps and a quad-turbocharged hybrid powertrain.',
    price: 5500,
    unlocked: false,
    stats: {
      topSpeed: 305,
      acceleration: 9.4,
      handling: 9.0,
      nitroCapacity: 9.2,
    },
    primaryColor: '#ffb700', // Sun Gold
    availableColors: ['#ffb700', '#00ffff', '#ff0033', '#111111', '#7b2cbf'],
    underglowColor: '#ff9900',
    modelType: 'supercar',
  },
  {
    id: 'solaris-formula',
    name: 'Solaris Formula',
    tier: 'PROTOTYPE',
    description: 'Experimental endurance prototype delivering unmatched ground effect downforce and pure velocity.',
    price: 9000,
    unlocked: false,
    stats: {
      topSpeed: 340,
      acceleration: 10.0,
      handling: 9.8,
      nitroCapacity: 10.0,
    },
    primaryColor: '#3a86ff', // Ultra Blue
    availableColors: ['#3a86ff', '#ff006e', '#8338ec', '#fb5607', '#ffffff'],
    underglowColor: '#00d4ff',
    modelType: 'prototype',
  },
];

export const INITIAL_MISSIONS: Mission[] = [
  {
    id: 'mission_dist_1000',
    title: 'First Milestone',
    description: 'Drive at least 1,000 meters in a single run.',
    category: 'distance',
    target: 1000,
    current: 0,
    rewardCoins: 150,
    completed: false,
    claimed: false,
  },
  {
    id: 'mission_coins_50',
    title: 'Coin Collector',
    description: 'Collect 50 gold coins on the highway.',
    category: 'coins',
    target: 50,
    current: 0,
    rewardCoins: 250,
    completed: false,
    claimed: false,
  },
  {
    id: 'mission_near_miss_10',
    title: 'Daredevil Pass',
    description: 'Perform 10 high-speed near-miss overtakes.',
    category: 'near_miss',
    target: 10,
    current: 0,
    rewardCoins: 350,
    completed: false,
    claimed: false,
  },
  {
    id: 'mission_speed_250',
    title: 'Sonic Barrier',
    description: 'Reach a top speed of 240 km/h or higher.',
    category: 'speed',
    target: 240,
    current: 0,
    rewardCoins: 300,
    completed: false,
    claimed: false,
  },
  {
    id: 'mission_dist_3000',
    title: 'Highway Legend',
    description: 'Survive 3,000 meters in Endless Mode.',
    category: 'distance',
    target: 3000,
    current: 0,
    rewardCoins: 600,
    completed: false,
    claimed: false,
  },
  {
    id: 'mission_coins_200',
    title: 'Treasury Vault',
    description: 'Collect 200 total coins across your careers.',
    category: 'coins',
    target: 200,
    current: 0,
    rewardCoins: 800,
    completed: false,
    claimed: false,
  },
];

export const DEFAULT_PLAYER_PROFILE: PlayerProfile = {
  coins: 250, // Starter bonus
  selectedCarId: 'apex-gtr',
  selectedDifficulty: 'medium',
  customCarColors: {},
  unlockedCarIds: ['apex-gtr'],
  highScores: {
    endless: 0,
    time_trial: 0,
    missions: 0,
  },
  bestDistances: {
    endless: 0,
    time_trial: 0,
    missions: 0,
  },
  totalGamesPlayed: 0,
  totalDistanceTraveled: 0,
  totalCoinsCollected: 0,
  totalNearMisses: 0,
  missions: INITIAL_MISSIONS,
};

export const DEFAULT_GAME_SETTINGS: GameSettings = {
  masterVolume: 0.8,
  musicVolume: 0.6,
  sfxVolume: 0.9,
  soundMuted: false,
  graphicsQuality: 'high',
  cameraShake: true,
  motionBlur: true,
  controlType: 'touch_buttons',
  cameraView: 'chase',
  defaultDifficulty: 'medium',
};
