import { DifficultyLevel, DifficultyConfig } from '../types';

export const DIFFICULTY_CONFIGS: Record<DifficultyLevel, DifficultyConfig> = {
  easy: {
    id: 'easy',
    label: 'EASY',
    badge: '1.0X',
    color: '#10b981', // Emerald
    bgColor: 'bg-emerald-500/20',
    borderColor: 'border-emerald-500/50',
    textColor: 'text-emerald-400',
    glowColor: 'rgba(16, 185, 129, 0.4)',
    scoreMultiplier: 1.0,
    coinMultiplier: 1.0,
    spawnInterval: 1.7,
    trafficBaseSpeedMin: 18,
    trafficBaseSpeedMax: 28,
    laneChangeProbability: 0.18,
    collisionForgiveness: 0.72,
    timeTrialStartTime: 45.0,
    timeTrialCheckpointBonus: 15.0,
    description: 'Relaxed highway cruising, wide overtaking gaps & forgiving clearances.',
  },
  medium: {
    id: 'medium',
    label: 'MEDIUM',
    badge: '1.5X',
    color: '#f59e0b', // Amber
    bgColor: 'bg-amber-500/20',
    borderColor: 'border-amber-500/50',
    textColor: 'text-amber-400',
    glowColor: 'rgba(245, 158, 11, 0.4)',
    scoreMultiplier: 1.5,
    coinMultiplier: 1.5,
    spawnInterval: 1.2,
    trafficBaseSpeedMin: 22,
    trafficBaseSpeedMax: 34,
    laneChangeProbability: 0.35,
    collisionForgiveness: 0.85,
    timeTrialStartTime: 35.0,
    timeTrialCheckpointBonus: 12.0,
    description: 'Standard cyber highway traffic flow with dynamic lane switches.',
  },
  hard: {
    id: 'hard',
    label: 'HARD',
    badge: '2.5X',
    color: '#f43f5e', // Rose / Red
    bgColor: 'bg-rose-500/20',
    borderColor: 'border-rose-500/50',
    textColor: 'text-rose-400',
    glowColor: 'rgba(244, 63, 94, 0.4)',
    scoreMultiplier: 2.5,
    coinMultiplier: 2.5,
    spawnInterval: 0.75,
    trafficBaseSpeedMin: 26,
    trafficBaseSpeedMax: 40,
    laneChangeProbability: 0.55,
    collisionForgiveness: 0.95,
    timeTrialStartTime: 25.0,
    timeTrialCheckpointBonus: 8.0,
    description: 'Intense rush hour traffic, high speeds & aggressive lane maneuvers.',
  },
};
